/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthProjectsIndexRouteImport } from './routes/_auth/projects/index'
import { Route as AuthProfileIndexRouteImport } from './routes/_auth/profile/index'
import { Route as AuthExperiencesIndexRouteImport } from './routes/_auth/experiences/index'
import { Route as AuthContactIndexRouteImport } from './routes/_auth/contact/index'
import { Route as AuthAnalyticsIndexRouteImport } from './routes/_auth/analytics/index'
import { Route as AuthProjectsDetailIdRouteImport } from './routes/_auth/projects/detail.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsIndexRoute = AuthProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileIndexRoute = AuthProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthExperiencesIndexRoute = AuthExperiencesIndexRouteImport.update({
  id: '/experiences/',
  path: '/experiences/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthContactIndexRoute = AuthContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAnalyticsIndexRoute = AuthAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsDetailIdRoute = AuthProjectsDetailIdRouteImport.update({
  id: '/projects/detail/$id',
  path: '/projects/detail/$id',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AuthIndexRoute
  '/analytics': typeof AuthAnalyticsIndexRoute
  '/contact': typeof AuthContactIndexRoute
  '/experiences': typeof AuthExperiencesIndexRoute
  '/profile': typeof AuthProfileIndexRoute
  '/projects': typeof AuthProjectsIndexRoute
  '/projects/detail/$id': typeof AuthProjectsDetailIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AuthIndexRoute
  '/analytics': typeof AuthAnalyticsIndexRoute
  '/contact': typeof AuthContactIndexRoute
  '/experiences': typeof AuthExperiencesIndexRoute
  '/profile': typeof AuthProfileIndexRoute
  '/projects': typeof AuthProjectsIndexRoute
  '/projects/detail/$id': typeof AuthProjectsDetailIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/analytics/': typeof AuthAnalyticsIndexRoute
  '/_auth/contact/': typeof AuthContactIndexRoute
  '/_auth/experiences/': typeof AuthExperiencesIndexRoute
  '/_auth/profile/': typeof AuthProfileIndexRoute
  '/_auth/projects/': typeof AuthProjectsIndexRoute
  '/_auth/projects/detail/$id': typeof AuthProjectsDetailIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/'
    | '/analytics'
    | '/contact'
    | '/experiences'
    | '/profile'
    | '/projects'
    | '/projects/detail/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/analytics'
    | '/contact'
    | '/experiences'
    | '/profile'
    | '/projects'
    | '/projects/detail/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/register'
    | '/_auth/'
    | '/_auth/analytics/'
    | '/_auth/contact/'
    | '/_auth/experiences/'
    | '/_auth/profile/'
    | '/_auth/projects/'
    | '/_auth/projects/detail/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/': {
      id: '/_auth/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthProjectsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile/': {
      id: '/_auth/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/experiences/': {
      id: '/_auth/experiences/'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof AuthExperiencesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/contact/': {
      id: '/_auth/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AuthContactIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/analytics/': {
      id: '/_auth/analytics/'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthAnalyticsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/detail/$id': {
      id: '/_auth/projects/detail/$id'
      path: '/projects/detail/$id'
      fullPath: '/projects/detail/$id'
      preLoaderRoute: typeof AuthProjectsDetailIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthAnalyticsIndexRoute: typeof AuthAnalyticsIndexRoute
  AuthContactIndexRoute: typeof AuthContactIndexRoute
  AuthExperiencesIndexRoute: typeof AuthExperiencesIndexRoute
  AuthProfileIndexRoute: typeof AuthProfileIndexRoute
  AuthProjectsIndexRoute: typeof AuthProjectsIndexRoute
  AuthProjectsDetailIdRoute: typeof AuthProjectsDetailIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthAnalyticsIndexRoute: AuthAnalyticsIndexRoute,
  AuthContactIndexRoute: AuthContactIndexRoute,
  AuthExperiencesIndexRoute: AuthExperiencesIndexRoute,
  AuthProfileIndexRoute: AuthProfileIndexRoute,
  AuthProjectsIndexRoute: AuthProjectsIndexRoute,
  AuthProjectsDetailIdRoute: AuthProjectsDetailIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
